#include <stdio.h>
#include <stdbool.h>
#include <string.h>

#define q(a) printf("  %d\n", a)
#define WGRN  "\x1B[32m"
#define WYEL  "\x1B[33m"
#define WBLU  "\x1B[34m"
#define WNRM  "\x1B[0m"

typedef enum {
    PUSH_INT,
    SAVE_LOCAL,
    ADD_INT,
    DISPLAY,
    EXIT
} Opcode;

const size_t arity[] = {
    1, // PUSH_INT
    1, // SAVE_LOCAL
    0, // ADD_INT
    0, // DISPLAY
    0 // EXIT
};

const char* opcode_names[] = {
    "PUSH_INT",
    "SAVE_LOCAL",
    "ADD_INT",
    "DISPLAY",
    "EXIT"
}; // autogenerated if echo opcode

const int program[] = {
    PUSH_INT, 2,
    PUSH_INT, -4,
    ADD_INT,
    DISPLAY,
    EXIT
};

size_t ip = 0;
int sp = -1;
bool DEBUG = true;

int fetch() {
    return program[ip];
}

bool active = true;

int stack[256];
int env[256];

bool touched[256];
size_t t = 0;

void eval(int j) {
    switch (j) {
        case EXIT:
            active = false;
            break;

        case SAVE_LOCAL:
            env[program[++ip]] = stack[sp];

            if (DEBUG) {
                size_t e;
                bool new_local = true;
                for(e = 0;e < t; e++) {
                    if (touched[e] == program[ip]) {
                        new_local = false;break;
                    }
                }
                if (new_local) {
                    touched[t] = program[ip];
                    t++;
                }
            }
            sp--;
            break;

        case PUSH_INT:
            stack[++sp] = program[++ip];
            break;

        case ADD_INT:
            stack[sp - 1] = stack[sp - 1] + stack[sp];
            sp--;
            break;

        case DISPLAY:
            printf("%d\n", stack[sp]);
            sp--;
            break;
    }
}

// echoes stack and ins info after j
void echo_stack(int j) {
    printf("%safter %s", WBLU, opcode_names[j]);
    int m;
    if (arity[j] > 0) {
        printf("(");
        for(m = 0;m < arity[j]; m++) {
            printf("%d", program[ip - arity[j] + m]);
            if (m < arity[j] - 1) { printf(" "); }
        }
        printf(")");
    }
    if (arity[j] == 0) {
        printf("\t\t\t");
    } else {
        printf("\t\t");
    }

    
    printf("%slocals:[", WYEL);
    for(m = 0; m < t; m++) {
        printf("%d: %d", touched[m], env[touched[m]]);
        if (m < t - 1) { printf(" ");}
    }
    printf("] ");

    printf("%sstack: [", WGRN);
    for(m = 0;m < sp + 1; m++) {
        printf("%d", stack[m]);
        if (m < sp) { printf(" "); }
    }
    printf("]");
    printf("%s\n", WNRM);
}

int main(int argc, char* argv[]) {
    int j;

    DEBUG = (argc > 1) && (strcmp(argv[1], "h") == 0);
    while (active) {
        j = fetch();
        eval(j);
        if (DEBUG) {
            echo_stack(j);
        }
        ip++;
    }
    return 0;
}
